<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>[Python API Design] #api #design #python</title>
<link rel="stylesheet" type="text/css" href="../assets/css/styles.css">
</head>
<body>
<div class="container">
<a href="../index.html" class="back-link">&laquo; Back to Index</a>
<h1 id="python-api-design-api-design-python">[Python API Design] #api #design #python</h1>

<p><a href="https://gist.github.com/Integralist/ee8e14571d9781cd74f1b1e8052f3c65" target="_blank">View original Gist on GitHub</a></p>

<h2 id="python-api-design-md">Python API Design.md</h2>

<h2 id="rules">Rules</h2>

<ol>
<li>Raise exceptions near to the source of the error.</li>
<li>Raise custom exceptions that are a subclass of a custom parent exception.</li>
<li>Catch the custom parent exception near the top level of your application.</li>
<li>Return <code>True</code> if an otherwise impure/side-effect driven operation succeeded.</li>
<li>Send (and document) standardized error messages (e.g. <code>NOUN_STATE</code> == <code>INPUT_INVALID</code>)</li>
<li>Send appropriate response status codes so callers can handle errors without parsing response structure.</li>
</ol>

<h2 id="example">Example</h2>

<pre><code class="language-py">class CustomError(Exception):
	def __init__(self, exc='exception raised', code=500):
		super().__init__(exc)
		self.code = code
        
class NetworkException(CustomError):
	pass
    
# example function that raises a subclass exception...

def call_something_that_will_error() -&gt; bool:
	# we catch the exception near the source of where it happened...
	try:
    	some_built_in_network_exception_fires('bad_url')
    except Exception as exc:
    	raise NetworkException('whoops!', code=400)
        
    # let's pretend this function would otherwise mutate a table record,
    # in that case we want to know it succeeded
    return True
    
# somewhere near your application's top-level entry point...

def app_entry_point():
	try:
		call_something_that_will_error()
	except CustomError as err:
		# although NetworkException was raised, 
		# we catch the parent custom exception
		#
		# also, we set an appropriate response status code,
		# which means regardless of our actual body's response structure
		# the caller of this API only needs to check the status code
		set_status(500)
		return {'state': 'error', code: 500, 'message': GENERIC_MESSAGE}
        
   	return {'state': 'success'}
</code></pre>
<link rel="stylesheet" href="../assets/css/highlights/github.min.css">
<script src="../assets/js/highlight.min.js"></script>
<script>hljs.highlightAll();</script>

</div>
</body>
</html>